const MENU = [
  {
    type: "Pizza",
    name: "Pesto Pizza",
    categories: ["Vegetarian"],
    ingredients: ["Genoese pesto", "pine nuts", "olives"],
    price: 8,
    image: "Images/Pizza-pesto-et-tomates-cerises-1-800x600.jpeg",
  },
  {
    type: "Pizza",
    name: "Sarda",
    categories: ["Spicy"],
    ingredients: ["mozzarella", "pecorino cheese", "spicy salami"],
    price: 9,
    image: "Images/sarda.jpeg",
  },
  {
    type: "Pizza",
    name: "Pizza Romana",
    categories: ["Vegetarian"],
    ingredients: ["mozzarella", "anchovies", "capers", "oregano"],
    price: 9,
    image: "Images/Pizza-Romana-1-800x477.jpeg",
  },
  {
    type: "Pizza",
    name: "Pizza Napoletana",
    categories: ["Vegetarian"],
    ingredients: ["mozzarella", "tomato", "oregano", "anchovies"],
    price: 8,
    image: "Images/napoletana.jpeg",
  },
  {
    type: "Pizza",
    name: "Four seasons pizza",
    categories: ["Comfort food"],
    ingredients: ["artichokes", "tomatoes", "basil", "mushrooms", "ham"],
    price: 11,
    image: "Images/four-seasons-pizza.jpeg",
  },
  {
    type: "Pasta",
    name: "Pasta Carbonara",
    categories: ["Comfort food"],
    ingredients: ["egg", "lardons", "Pecorino romano"],
    price: 8,
    image: "Images/pasta-carbonara_b-864x413.jpeg",
  },
  {
    type: "Pasta",
    name: "Spaghetti bolognese",
    categories: ["Comfort food"],
    ingredients: ["beef", "chopped tomatoes", "garlic"],
    price: 8,
    image: "Images/bolognaise.jpeg",
  },
  {
    type: "Pasta",
    name: "Lasagna bolognese",
    categories: ["Comfort food"],
    ingredients: ["mozzarella", "tomato", "beef"],
    price: 10,
    image: "Images/lasagna-bolognese.jpeg",
  },
  {
    type: "Pasta",
    name: "Cacio e pepe",
    categories: ["Vegetarian"],
    ingredients: ["pecorino romano", "black pepper"],
    price: 9,
    image:
      "Images/Spaghetti-Cacio-e-Pepe-Pecorino-and-black-pepper-spaghetti_1200x800.jpeg",
  },

  {
    type: "Desserts",
    name: "Torrone Semifreddo",
    categories: ["Desserts"],
    ingredients: ["honey", "egg whites", "nuts"],
    price: 4,
    image: "Images/Torrone Semifreddo.jpeg",
  },
  {
    type: "Desserts",
    name: "Mixed-Nut-Milk Panna Cotta",
    categories: ["Desserts"],
    ingredients: ["nut milk", "honey", "strawberry jam"],
    price: 10,
    image: "Images/pannacotta.jpeg",
  },
  {
    type: "Desserts",
    name: "Chocolate and Pistachio Biscotti",
    categories: ["Desserts"],
    ingredients: ["dark chocolate", "egg", "nuts"],
    price: 9,
    image: "Images/biscotti.jpeg",
  },
];
